# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno-snapshot"
version = "2.1.5"
authors.workspace = true
default-run = "deno-snapshot"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Creates snapshots for building the Deno executable"

[dependencies]
deno_runtime = { workspace = true, features = ["include_js_files_for_snapshotting", "only_snapshotted_js_sources"] }
deno_core = { workspace = true, features = ["include_js_files_for_snapshotting"] }
